### ISSUE TITLE
WMFJS issue when importing as a module

### ISSUE THREAD

**Issue by joeypedicini92** [tbluemel/rtf.js#42]
Error: `jquery__WEBPACK_IMPORTED_MODULE_0__(...).svg is not a function`

When trying to open RTF files that use WMFJS, I get this error. It occurs at: https://github.com/tbluemel/rtf.js/blob/master/src/wmfjs/Renderer.ts#L50

Seems to be that jquery.svg.js isn't getting imported correctly? 

And this only occurs if I import rtf.js as a module. If I load the scripts from HTML there is no problem.

**Comment by zoehneto** [comment]
Could you please post a minimal sample which reproduces this issue? I have used rtf.js as a module successfully with webpack in the past (which is what the code sample in the `Getting Startet` guide was taken from), but it may well be that it doesn't work correctly with other bundlers (specifically because of the jquery plugins).

**Comment by joeypedicini92** [comment]
Yeah we're using ember which uses broccoli could be related to that

**Comment by zoehneto** [comment]
I just created a little repo to show how it works with webpack at [https://github.com/zoehneto/rtf.js-sample-webpack/tree/master](https://github.com/zoehneto/rtf.js-sample-webpack/tree/master) . I'm not familiar with ember / ember cli so I need a minimal reproduction to help you here.

**Comment by Valterrsj** [comment]
I'm getting the same problem when trying to import the module into a project with vuejs and electron-builder ... To reproduce:
- install vue-cli 3
- create new project with vue-cli 3: vue create newproject
- enter the project folder: cd newproject
- add electron-builder (select eletron 5.0): vue add electron-builder
- import rtf.js into the background.js file: import {EMFJS, RTFJS, WMFJS} from 'rtf.js';
- start the development server: npm run electron: serve
I got this error:
App threw an error during load
TypeError: $ .extend is not a function
    at Object.eval (webpack: ///./node_modules/rtf.js/dist/jquery.svg.js?: 36: 7)
    at eval (webpack: ///./node_modules/rtf.js/dist/jquery.svg.js?: 13: 37)
    at eval (webpack: ///./node_modules/rtf.js/dist/jquery.svg.js?: 16: 2)
    at Object .. / node_modules / rtf.js / dist / jquery.svg.js (C: \ ... \ ... \ .... \ dist_electron \ index.js: 1318: 1)
    at __webpack_require__ (C: \ ... \ ... \ ... \ .... \ dist_electron \ index.js: 20: 30)
    at webpackUniversalModuleDefinition (webpack: ///./node_modules/rtf.js/dist/EMFJS.bundle.js?: 3: 28)
    at eval (webpack: ///./node_modules/rtf.js/dist/EMFJS.bundle.js?: 5: 3)
    at Object .. / node_modules / rtf.js / dist / EMFJS.bundle.js (C: \ ... \ ... \ .... \ dist_electron \ index.js: 1285: 1)
    at __webpack_require__ (C: \ ... \ ... \ ... \ .... \ dist_electron \ index.js: 20: 30)
    at webpackUniversalModuleDefinition (webpack: ///./node_modules/rtf.js/dist/RTFJS.bundle.js?: 3: 103)

**Comment by zoehneto** [comment]
@Valterrsj I followed your steps:

- `npm install -g @vue/cli`
- `vue create newproject`
- `cd newproject/`
- `vue add electron-builder`
- `npm i rtf.js`

- add `import {EMFJS, RTFJS, WMFJS} from 'rtf.js';` to background.js

- `npm run electron:serve`

Which gives me the following output, suggesting that everything works just fine:
```
> newproject@0.1.0 electron:serve /home/zoehneto/tmp/newproject
> vue-cli-service electron:serve

 INFO  Starting development server...
 98% after emitting CopyPlugin                                                   

 DONE  Compiled successfully in 1971ms                                                                                                                                                                                                   6:08:18 PM

 
  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.178.36:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

⠴  Bundling main process...

 DONE  Compiled successfully in 810ms                                                                                                                                                                                                    6:08:19 PM

  File                      Size                     Gzipped

  dist_electron/index.js    2838.34 KiB              1182.02 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
```

I assume you added some code which actually uses rtf.js in order to get your error and didn't just import the library (without that code I can't reproduce your issue). But if I understand this vue / electron project setup correctly, the `background.js` script is actually run by node.js and only starts the browser side of electron (hence the `new BrowserWindow`) meaning that running rtf.js there will not work as you don't have the DOM available, which is needed by jQuery (might be why it doesn't load). So either you run rtf.js in the BrowserWindow created in `background.js` or if it needs to happen on the node side you have to use jsdom as described [here](https://github.com/tbluemel/rtf.js/blob/master/GETTING_STARTED.md#node-using-jsdom).

**Comment by Valterrsj** [comment]
Thank you! I solved it importing directly into render component as you said!!
