### ISSUE TITLE
Japanese language renders incorrectly

### ISSUE THREAD

**Issue by rajsite** [tbluemel/rtf.js#44]
I created some text in Japanese that I loaded into Windows 10 WordPad and saved as an RTF document. When I close and open the RTF document in WordPad everything appears to render correctly. When I load the RTF in RTF.js using the demo page in Chrome, Firefox, IE, or Edge it looks very different and appears corrupted.

Screenshot:
![image](https://user-images.githubusercontent.com/1588923/64057406-17521680-cb62-11e9-94da-66cc7833ab3a.png)

Using the demo page here: https://tbluemel.github.io/rtf.js/samples/01_rtf/rtf.html
And generated Japanese text here: http://generator.lorem-ipsum.info/_japanese

Any suggestions for how to have it render correctly? Is there some setting I need to configure?

The following is an example rtf file with Japanese text: [japanese lorum ipsum.zip](https://github.com/tbluemel/rtf.js/files/3561941/japanese.lorum.ipsum.zip)

**Comment by zoehneto** [comment]
The problem here was incomplete support for double width characters as used by Japanese and other Asian languages. Rtf supports two ways of using double width characters in a document: a document can either specify it explicitly (which was already supported) or let the reading application figure it out based on the hex value of the following character (which was not supported). I have added support for this second method to rtf.js in version 2.3.2 which makes your document display correctly.

**Comment by rajsite** [comment]
@zoehneto Thank you for the quick reply! :) Unfortunately when I try to use v2.3.2 with the provided example document I still see some errors.

I tried to highlight the characters that looked the same between the WordPad representation and the rtf.js representation in the following image:
![differences_with_2 3 2](https://user-images.githubusercontent.com/1588923/64061959-ac76fe80-cba6-11e9-8a2b-18941ace57ba.PNG)

**Comment by rajsite** [comment]
One test I find handy for i18n strings is the pile of poo test: `Iñtërnâtiônàlizætiøn☃💩` as described in the [JavaScript has a Unicode problem](https://mathiasbynens.be/notes/javascript-unicode) blog.

This is the result of the pile of poo test with v2.3.2

![image](https://user-images.githubusercontent.com/1588923/64062107-75a1e800-cba8-11e9-867f-e9f70d1c003d.png)

The following is the test rtf doc: [pileofpootest.zip](https://github.com/tbluemel/rtf.js/files/3562287/pileofpootest.zip)

**Comment by zoehneto** [comment]
Good catch, I misunderstood the spec about ranges for the leading and trailing byte (turns out they are a) different and b) specific to each codepage). I have committed a solution which works with your file and also with all the existing tests but it's kind of hackish and I would really appreciate you testing this if you have test files in Japanese (also always appreciate people contributing test files, since that is the best way to avoid accidental breakage).

The pile of poo example is a different issue, as described in the post you linked to we'd have to add support for surrogate pairs. That would involve a bit of a rework of the symbols support and some trickery to support parsing two keyword into one result, for which I don't have time right now, but I would like to revisit that at some point (of course PRs are always welcome).

**Comment by rajsite** [comment]
@zoehneto Thanks again! I tested against master locally and the Japanese Lorem Ipsum does look accurate! I don't have access to some of the other rtf language files at the moment but I can get back to you mid next week and hopefully I can share some examples.

**Comment by NIbbuchanan** [comment]
Good timing. I just started doing some testing and this is a fantastic tool! I did have some problems with localized fonts not converting correctly, and in some cases producing errors in the conversion tool. I a
[Localized Text.zip](https://github.com/tbluemel/rtf.js/files/3569723/Localized.Text.zip)
ttached a zip with a sample RTF to test as well as additional information about how to write localized text and interpret it. Hope this helps.
Thanks, Brad

**Comment by rajsite** [comment]
@zoehneto the examples from @NIbbuchanan should be representative of the use cases, we have been working on a project together that leverages rtf.js

**Comment by zoehneto** [comment]
@rajsite @NIbbuchanan thank you for your examples. I have finally had the time to do a refactoring of the text processing code and to look deeper into the issues raised by your test files. With PR #46 everything should now be handled correctly. It would be great if you could test the new code :)

**Comment by zoehneto** [comment]
I have just published a new version which includes the improvements of the PR.

**Comment by rajsite** [comment]
@zoehneto sorry for not getting back to you and thanks for all of your help!

Unfortunately our requirements shifted and we are no longer using an rtf representation but I wanted to thank you again for all of the work you have put into rtf.js and the support you gave when we were experimenting with it. I'll definitely keep it in mind for the future :)
